### ISSUE TITLE
Extensions to incorporate additional information/metadata from user via ARS

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/ReasonerAPI#103]
As per [the slack discussion](https://ncatstranslator.slack.com/archives/C011ZDHCQBC/p1587057677006700), opening this issue at the request of @patrickkwang to discuss extensions to incorporate user metadata. In particular:

The ARS will ostensibly be using the ReasonerStdAPI to pass queries to ARAs, so:

1.  The ARS may desire to pass along information to the ARAs about what “gaps need to be filled”, what needs to be “cleaned up”, how the graph is to be “enriched” etc.
2.  The ARS may desire to indicate what the end user is actually desiring (eg. with a complicated query graph, the “essence” of a result depends entirely on what the end user intends to receive back as answers)
3. How shall the Reasoner Standard API be modified in order to allow the ARS to pass this valuable “extra information” along to the ARAs?
4. What are the "valuable pieces of extra information/metadata"?

@edeutsch may want to weigh in as well given our previous discussions on the topic.

**Comment by edeutsch** [comment]
Is this handled by Op&Wf? okay to close?
