### ISSUE TITLE
Representing Contextual (Clinical) Queries

### ISSUE THREAD

**Issue by stevencox** [NCATSTranslator/ReasonerAPI#104]
#### Issue
Clinical knowledge sources are vital to Translator but there's no way to query one with the ReasonerStdAPI and therefore, the ARS.
#### Context
Clinical data sources are  specific cases of contextual knowledge sources. They allow the user to specify circumstances on which the resulting  knowledge graph is contingent. For clinical data sources, that context is a cohort.
#### Background
Developed in the feasibility phase, the [TranQL](https://researchsoftwareinstitute.github.io/data-translator/apps/tranql) query tool spans clinical and non-clinical sources using the ReasonerStdAPI. At the time, the API supported an `options` element which provided the flexibility to provide service specific parameters. The options element has since been removed.

A query could be built with options  specific to a particular clinical knowledge provider like ICEES or COHD as shown in this figure:
![image](https://user-images.githubusercontent.com/306971/83825578-b256be80-a6a7-11ea-918d-3d4b31fab06e.png)

[TranQL](https://tranql.renci.org/) strips the `icees.` prefix and routed those settings as `options` in a ReasonerStdAPI invocation to the ICEES clinical KP. In principle, a similar approach would work with other KPs.

#### Assorted Considerations
1. **Generality**: There is an argument for extending the ReasonerStdAPI in a clinical KP specific way to support this  functionality. Personally, I think we should resist the urge to create an enormous API specification. The options capability is an extremely general and flexible mechanism for passing service specific information. 
2.  **Cohort Specification Standardization**: Suppose an ARS poses a question with a clinical dimension. For what kinds of questions is it meaningful to route that question to multiple clinical KPs? i.e. are there useful cohort definitions that both ICEES and COHD can resolve?
3. **Operations**: There are a great many things one might want a clinical (or other contextual) KP to do with a result set. It could be rendered as a graph. It could be asked to decorate, or overlay an existing graph with p values indicating the degree of association within a cohort. Can the ReasonerStdAPI provide a way to identify a desired operation on the data being requested of the clinical KP?

#### Approach 1: Question Explicitly Involves Contextual Features.
* **The Question**: It would be great if @karafecho and Casey Ta would team-outline a clinical query to be posed to the ARS.
* **The ARS**: The ARS formats the question to include a cohort specification representing the question and distributes it to the ARAs.
* **The ARA**: @patrickkwang of ARAGORN and another ARA (volunteers?) take the ARS message from the message bus and distribute it to the appropriate clinical data sources.
* **The Clinical KPs**: The clinical KPs construct the appropriate cohorts and return kgs. @xu-hao 
* **Design Implications**:
  * Restore the options field of the Message object.
  * Represent cohorts as name value pairs or other very simple/general representation.
* **Tradeoff**: Challenging to express fine grained contextual parameters - but possible.

#### Approach 2: KP Resolves Biolink Query Elements to Contextual Features.
* **The Question** contains no inherently contextual or clinical data.
* **The ARS** distributes the question to the message bus.
* **The ARA** determines that enhancing a question with contextual knowledge would be useful and sends a Message to a contextual KP.
* **The KP** 
  * resolves Biolink Model types in the input question to context defining features to automatically construct a cohort.
  * returns a graph contingent on that context.
* **Design Implications**:
  * Change nothing in RSA.
  * Contextual KPs map Biolink types to their feature space.
* **Tradeoff**: Easy to use but no way to specify fine grained contextual parameters.

**Comment by karafecho** [comment]
@stevencox : Please see this related [doc](https://docs.google.com/document/d/1VWIMmaLfw3YJeJDMElkUyh8095rYwDa7rb4nwwCbuPo/edit?usp=sharing) (from Clinical Data Working Group).

**Comment by karafecho** [comment]
**From the doc linked above:**

**Clinical KP Translator Standard API Endpoints**

*ICEES+ Exposures Provider*
Translator Standard APIs:
2 * N associations KG:
url: https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph
One-hop KG:
url: https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph_one_hop 
Overlay KG:
url: https://icees.renci.org:16340/apidocs/#/default/post_knowledge_graph_overlay
Additional information and example queries can be found here 

*COHD Clinical Data Provider*
http://cohd.io/api 
Translator Reasoner Standard API
http://tr-kp-clinical.ncats.io/api/translator/query
Note: Compliant with Translator Reasoner Standard API v0.9.2, but not compliant with recent changes to Reasoner Standard API
Endpoints leveraging contextual temporal information:
Age distributions of clinical concepts
http://tr-kp-clinical.ncats.io/api/temporal/conceptAgeCounts
Temporal delta distributions between pairs of clinical concepts
http://tr-kp-clinical.ncats.io/api/temporal/conceptPairDeltaCounts
Search for concepts with similar age distributions to a given concept
http://tr-kp-clinical.ncats.io/api/temporal/findSimilarAgeDistributions
Search for concepts with significant temporal associations to a given concept
http://tr-kp-clinical.ncats.io/api/temporal/sourceToTarget 

*Multi-omics Provider*
http://biggim.ncats.io/api/#!/translator/post_translator_query

[This is the Big GIM endpoint. Translator Standard API is under development and will be located elsewhere.]

*Connections Hypothesis Provider*
[To be added]

**Comment by edeutsch** [comment]
I believe this issues is addressed by merge PR #222. @cbizon okay to close?

**Comment by edeutsch** [comment]
Implemented in TRAPI 1.1
Closing.
