### ISSUE TITLE
Re-name NCATS-ReasonerStdAPI

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#115]
We'd like to do this in concert with the move from the NCATS-Tangerine group to the NCATSTranslator group so that any technical juggling can happen just once.

We will also unify the naming across the repository, the `TranslatorReasonersAPI.yaml` file, and the documentation.

Please comment with suggestions!

**Comment by ehinderer** [comment]
I heard someone suggest "TranslatorAPI." That person read my mind.

**Comment by patrickkwang** [comment]
"Translator API" is clear and simple. My only concern is that it may not be specific enough. Are the SmartAPI-annotated, non-standardized KP APIs not Translator APIs? What about the interface that the ARS provides?

**Comment by patrickkwang** [comment]
One option is just "Reasoner API" (in contrast with other variations "[NCATS/Translator] Reasoner [Std] API"). We'd have to accept that we're co-opting this term "reasoner" from any rational usage (including the tools from the feasibility phase) and that it's not descriptive in the least. But this has the advantage that everyone in Translator will already know what we're talking about.

**Comment by patrickkwang** [comment]
Another option is something descriptive like "Query Graph API".

**Comment by edeutsch** [comment]
> "Translator API" is clear and simple. My only concern is that it may not be specific enough. Are the SmartAPI-annotated, non-standardized KP APIs not Translator APIs? What about the interface that the ARS provides?

I like "Translator API".
It is not clear to me that "SmartAPI-annotated, non-standardized KP APIs" should be called "Translator APIs". I would call them "SmartAPIs" or "Translator SmartAPIs". As opposed to THE "Translator API".
The interface that the ARS provides would also use the "Translator API" I would say. I think we aim it to be the same?
I think "Translator API" is the best option I've seen so far. Feel free to disagree or suggest others.

**Comment by andrewsu** [comment]
I like "Translator Graph API" and "Translator SmartAPI", because the graph nature is one distinguishing feature between the two approaches. (On the other hand, Translator Graph APIs could also be registered in the SmartAPI registry, so that is a potential confusion...)

**Comment by vdancik** [comment]
We can call it Knowledge-Exchange API (KEXAPI)
