### ISSUE TITLE
Guidance for server behavior

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#133]
This standard defines the accepted interfaces for a Translator component, but does little to describe the expected behavior of a server implementing the Reasoner API. For example, a server may be technically compliant with the standard which, upon receiving any query, always responds with `{}` (this is a Message without any properties - none are `required`). Realistic questions to be answered include whether a server should always return the same query graph it received (#66), or what subset of elements in the query graph are expected to be bound in each result (at least one edge? exactly one? all of them?).

I think we need a document describing the expected behavior of the server, in addition to the format of its inputs and outputs.

**Comment by edeutsch** [comment]
agreed, this is something we should document.

**Comment by patrickkwang** [comment]
Closing in favor of #152.
