### ISSUE TITLE
Add metadata endpoint

### ISSUE THREAD

**Issue by vdancik** [NCATSTranslator/ReasonerAPI#142]
We should add a metadata endpoint, say /info, that would return information what server is and what it can do:

```
{
    "title": "best ARA ever",
    "description": "This is the best ARA ever.",
    "version": "1.1.0",
    "TRAPI": {
        "version": "1.0.0",
        "synchronous support": true,
        "asynchronous support": false,
        "callback support": false,
        "batch support": true,
        "extended": true,
        "supported operations": ["query"]
    }
}
```

**Comment by vdancik** [comment]
Adding "supported operations" as suggested by @cbizon

**Comment by newgene** [comment]
@vdancik a general comment is I would not include whitespace in the field names and replace it with `_` to make it one word.

Some general fields like `version` are also available from standard OpenAPI as `info.version` field, so you might have two places to put the same info. Alternative is to put additional TRAPI info within API metedata:

```
info:
  description: "This is the best ARA ever."
  title: "best ARA ever"
  version: "1.1.0"
  x-trapi:
           "TRAPI": "1.0.0",
           "synchronous support": true,
           "asynchronous support": false,
           "callback support": false,
           "extended": true,
           "supported operations": ["query"],
           "KGX export URL": null
```

But I can see an argument to have everything in a self-contained endpoint, so I am fine either way, just need to keep duplicated info in-sync.

**Comment by patrickkwang** [comment]
This `x-trapi` OpenAPI extension would be a good way to include this sort TRAPI-specific, service-level information. It might could be a bit more concise if the fields "synchronous support", "asynchronous support", "callback support", and "batch support" are inferred from the presence or absence of the associated endpoints:
`/query/sync` (this is the current synchronous interface),
`/query/async/pull` (asynchronous interface with polling),
`/query/async/push` (asynchronous interface with callback),
and batch versions: `/batch/query/sync`, `/batch/query/async/pull`, `/batch/query/async/push`.

**Comment by edeutsch** [comment]
addressed with x-trapi
