### ISSUE TITLE
Allow query to specify 'operation'

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#152]

**Comment by patrickkwang** [comment]
Operations may include things like those provided by [ARAXi](https://github.com/RTXteam/RTX/blob/458c88eab5dc3c610457757c3c24446379ec1a6b/code/ARAX/Documentation/DSL_Documentation.md): expand(), overlay(), filter_kg(), filter_results(), etc.

Each operation definition should include information about:
1. how existing answers should be handled (#49)
2. whether the query graph can/should be modified (#66)

**Comment by kevinxin90** [comment]
@patrickkwang Wondering where can I find query examples for these special TRAPI operations mentioned above and where to specify this "operation" in the query? Thanks!

**Comment by patrickkwang** [comment]
@kevinxin90 There is no consensus on how these should be represented yet. The Operations working group is... working on it.

**Comment by dkoslicki** [comment]
@edeutsch @patrickkwang The December demo working group asked me to make this high priority so we can send operations via the ARS. Is this on the roadmap for a future version of TRAPI?

**Comment by dkoslicki** [comment]
Forgot to tag this PR: #200

**Comment by edeutsch** [comment]
It is in our prioritization list:
https://github.com/NCATSTranslator/ReasonerAPI/discussions/251#discussioncomment-787535
although not ranked especially highly yet.
But I will see that it is in TRAPI 1.2 formally, yes.

But the good news is that it can be added to a TRAPI 1.1 implementation via additionalProperties without any schema change as long as we all agree on those additions. ARAX and Aragorn already support workflow[] in current queries, so there is no substantial impediment to using this already.

**Comment by edeutsch** [comment]
This was addressed in PR #262. Closing.
