### ISSUE TITLE
How do we access/specify the different format versions?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#155]
Maybe one key detail that we need to decide on is how we are going to migrate from 0.9.2 to 1.0

Currently our endpoint is this:
https://arax.rtx.ai/api/rtx/v1/query
In the response Message, you will see this:
  "schema_version": "0.9.3",
following the `extended` schema here https://github.com/NCATSTranslator/ReasonerAPI/blob/8a65716f141a3e59a9299585c40b30ca2c59fc58/API/TranslatorReasonersAPI.yaml#L365

When we switch our support from 0.9.3 to 1.0, what would be the expectation?

Would we use the same endpoint, but the payload would say:
  "schema_version": "1.0.0",
and the client would have to figure out what to do?

Or should we have different endpoints for different schema versions?
Should we have:
https://arax.rtx.ai/apis/trapi/v0.9.3/query
https://arax.rtx.ai/apis/trapi/v1.0/query
and the inevitable:
https://arax.rtx.ai/apis/trapi/v1.0.1/query
and the eventual:
https://arax.rtx.ai/apis/trapi/v1.1/query

I am astoundingly lazy, so I would prefer one endpoint and the payload contains the produced (and requested?) version number. But others are probably not so lazy and would like to have multiple endpoints around multiple versions?

What do you think?

**Comment by brettasmi** [comment]
I mentioned this in the Slack channel today, but it seems relevant to this issue too: it would be great to have some guidance from standards on expected support lifecycles. It's unrealistic to expect that only a single version of TRAPI will be running at a given time, so it'd be good to know for when and for how long major versions should be supported. Knowing that information could help guide this decision.

That aside, I think TRAPI version number should probably be specified in the message with a `trapi_version` (or similar) key that the service can handle (or reject) appropriately. I don't think the clients should be responsible for knowing which minor version of the API route to query, rather they should just make clear the format of their message.

That said, I could see it being desirable to have major versions specified in the URL (`/api/v1/` for TRAPI 1.0, `/api/v2/` for TRAPI 2.0, etc), but those changes should be rare. However, services may want to reserve those for signaling major versions of their tools that indicate significant changes in query processing.

**Comment by vdancik** [comment]
Alternative approach is to have an endpoint that provides this information, see "Add metadata endpoint #142"

**Comment by edeutsch** [comment]
Seems like this is resolved.
