### ISSUE TITLE
Allow query to specify 'log level'

### ISSUE THREAD

**Issue by bill-baumgartner** [NCATSTranslator/ReasonerAPI#159]
PR #158 allows `LogEntry` objects to be included in the `Response` object. A `LogEntry` can specify a level as `ERROR`, `WARNING`, `INFO`, or `DEBUG`.  It may be convenient to allow a user to specify the level of logs to be returned, e.g. a developer may be interested in the `DEBUG` logs whereas a user may not.

**Comment by edeutsch** [comment]
PR #214 addresses this and is merged.
