### ISSUE TITLE
Recommended tools for API implementations

### ISSUE THREAD

**Issue by vdancik** [NCATSTranslator/ReasonerAPI#160]
As we are nearing to a release of 1.0 version of the API, I have a question - which tools are recommended for the code generation and API implementation and are verified to work properly?

**Comment by marcdubybroad** [comment]
Quick description of the issue I had when using java to generate the python code from the TranslatorReasonerAPI.yaml from the version tag: https://github.com/NCATSTranslator/ReasonerAPI/releases/tag/v1.0.0-beta

The code generation command is:
java -jar ~/Apps/Libs/OpenAPI/openapi-generator-cli.jar generate -i TranslatorReasonersAPI.yaml -g python-flask -o python-flask-server

A few model files (node, q_edge, q_node) made use of the openapi_server.models.one_ofstringarray object which was not generated, so caused compilation errors. The import statement is:
from openapi_server.models.one_ofstringarray import OneOfstringarray  # noqa: E501

To resolve the issue, we replaced the 'OneOfstringarray' instances with 'str'. 
Our v1.0 is up and running properly with the changes.
