### ISSUE TITLE
TRAPI Node and Edge properties are different from Biolink Model Node and Edge properties

### ISSUE THREAD

**Issue by deepakunni3** [NCATSTranslator/ReasonerAPI#161]
Biolink Model has `id`, `name`, `category` as core properties of a node in a graph. 
TRAPI specification has `id`, `name`, `type` as core properties of a TRAPI Node object.

Biolink Model has `edge_label`, `subject`, `object`, `relation` as core properties of an edge in a graph. 
TRAPI specification has `type`, `source_id`, `target_id`, `relation` as core properties of a TRAPI Edge object.

While the properties for each representation still means the same, there is still a need for a translation from Biolink Model representation (KGX serialization) to TRAPI representation.

Since TRAPI is on road to v1.0, is there a way we can address this before v1.0 becomes final?

CC'ing @edeutsch @patrickkwang @cbizon @vdancik @cmungall @RichardBruskiewich

**Comment by patrickkwang** [comment]
I agree it would be nice to have these unified, and sooner would be better than later. Detailed thoughts:

* I have no problem renaming `type` to `category` for nodes.
* Renaming `source_id` and `target_id` to `subject` and `object` is a good idea. The latter terms are more widely used, and it would reduce collisions with other uses, especially of "source".
* I'm confused about "edge_label". I'm looking [here](https://biolink.github.io/biolink-model/docs/Association) and can't find reference to any "label". Maybe that's not the place to look?

**Comment by deepakunni3** [comment]
@patrickkwang The edge_label is described here: https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L2090

Unfortunately this is not in the documentation site (a bug which will be addressed in the coming days).

There might be a bit of confusion here regarding an edge, biolink relation, and biolink Association.
I'll try to clarify this here for posterity.

The Biolink Model has four parts:
- Node types (For example:`biolink:Gene`, `biolink:Disease`)
- Edge types (For example: `biolink:GeneToDiseaseAssociation`, `biolink:GeneToGeneAssociation`)
- relations (For example: `biolink:contributes_to`, `biolink:interacts_with`)
- properties (node and edge properties)

Each edge in the model has two properties that describes the edge itself,
- `edge_label` (a high level relation from the Biolink Model)
- `relation` (a granular relation from ontologies like RO)

An edge can be considered to be of type `biolink:GeneToDiseaseAssociation` if the subject of that edge is a `biolink:Gene` node, the object of that edge is a `biolink:Disease` node, and the `edge_label` has a biolink relation that is meant to link a Gene to a Disease. Going by this explanation, the type of Association of an edge can be inferred by its properties.

If we were to serialize an edge HGNC:11603 --- biolink:related_to ---> MONDO:0015998, it would look like so:
```
subject: HGNC:11603
edge_label: biolink:related_to
object: MONDO:0015998
relation: RO:0000000
association_type: biolink:GeneToDiseaseAssociation
```
Here `association_type` means something completely different from `edge_label`. 
`association_type` is similar to `category` property of a node.

**Comment by vdancik** [comment]
Instead of `edge_label` and `type`, I would use `biolink_predicate` to make it explicit what we mean. I always assumed that biolink predicate (type of an edge or edge_label) must be from the `biolink:related_to` hierarchy.

**Comment by cmungall** [comment]
In retrospect, `predicate` should have been used.

I think making the change makes sense though it will cause a bit of churn

**Comment by TomConlin** [comment]
+1

**Comment by RichardBruskiewich** [comment]
+1 @cmungall ... I've often wondered about that! Exactly my thought: why didn't we call it *predicate*?
