### ISSUE TITLE
Nullable properties?

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#183]
Should we allow properties (e.g. `Node.name`) to take the value `null` (`None` in Python)? This is controlled by the `nullable` property in OpenAPI: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-20, which is false by default. Many languages and tools treat a missing key and a null value interchangeably: Javascript, pydantic, ... so it might be handy to allow that.

**Comment by edeutsch** [comment]
I am confused by this. I was under the impression (and I think ARAX works this way) that if a property is not required (like Node.name), then there is no distinction between null and not written out.

Am I understanding correctly that currently as written if we went by the book, a Node object with name=null is not permitted but a Node object with no mention of name is fine?

**Comment by patrickkwang** [comment]
That's correct. None of our properties can take the value `null`, regardless of whether they are required. I believe we can achieve the behavior we want by adding `nullable: true` to each of the non-required properties.

**Comment by edeutsch** [comment]
okay, thanks.
Yes, I assumed that missing was the same as nullable, so I would support adding nullable: true to all of these since I think this is the expected behavior for many people. This would be a proposed PR for 1.0?

**Comment by patrickkwang** [comment]
Turns out `nullable` is kind of a mess: https://github.com/OAI/OpenAPI-Specification/issues/1368
But this will mostly sorted out in OpenAPI 3.1!
