### ISSUE TITLE
What do category/predicate/id lists mean?

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#199]
Historically, these have been treated as logical disjunctions, which allows a limited sort of batch querying. If that is the intent, we should document it somewhere - perhaps in this repo, perhaps with Operations and Workflow, perhaps both.

Also, what does an empty list mean? Options:
1. An empty list is equivalent to a null value or a missing key.
2. To be consistent with the logical disjunction interpretation, there must be _no_ category/predicate/id for this element. This is nonsensical.
3. Nothing - do not allow empty lists.

**Comment by brettasmi** [comment]
I agree with your assessment and we are treating this as an `or` operator.

For empty list, we're interpreting treating them as `1`. We just iterate on the array and pull out what's in there; if nothing is there, the query becomes unrestricted on that given property. I wouldn't mind implementing `3` if we go down that path.

**Comment by edeutsch** [comment]
Empty lists for these properties are explicitly disallowed in TRAPI 1.1 under the agreed understanding that an empty list must mean item 2 above, and therefore the schema enforces item 3 above.
