### ISSUE TITLE
Capture Attributes Data from Multiomics Edges in Query

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/ReasonerAPI#206]
Issue: Multiomics provides a lot of data about p-values and disease context as attributes in the edge connecting the drug and gene wants to search or filter on these things, the data is returned but you cannot get to it from the query.  This may be better suited to Workflow and Operations, but putting this here for posterity.

https://docs.google.com/document/d/1tAYiIaS1ueer5ro3wjC-Rvt0aKx2UViF4kvW2hHZQeg/edit

**Comment by vdancik** [comment]
This is being addressed by a proposal in PR #157

**Comment by edeutsch** [comment]
Implemented in TRAPI 1.1
closing.
