### ISSUE TITLE
How shall servers react to an unrecognized additionalProperty on a QNode or QEdge?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#209]
The schema allows additionalProperties to QNode and QEdge.
JustFixIt saw an example where someone was observed passing QEdge.category and ARAX reacted with a WARNING but proceeded (by ignoring the QEdge.category)
ARAX is experimenting with additionalProperties 'option_group_id' and 'exclude'
There is talk of adding a QNode property to specify exact, narrow, or wide

How shall a server react when it receives an unrecognized additionalProperty on a QNode or QEdge?
Shall we standardize this?

**Comment by ehinderer** [comment]
Do you remember what the example was? I'm having trouble understanding the situation.

**Comment by edeutsch** [comment]
I don't remember the exact example, but it was effectively like this:
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "category": "biolink:physically_interacts_with"
      }
   },
   "nodes": {
      "n00": {
         "id":        "CHEMBL.COMPOUND:CHEMBL112",
         "category":  "biolink:ChemicalSubstance"
      },
      "n01": {
         "category":  "biolink:Protein"
      }
   }
}
```

**Comment by ehinderer** [comment]
So the solution was to ignore the edge's "category" attribute? And the question here is how a server should react to seeing an attribute **key** it doesn't recognize or an attribute **value**?

**Comment by edeutsch** [comment]
I intended this issue to be about an unrecognized *key*.
In this case, the server (ARAX) issues a warning:
 2021-02-17T20:46:23.499231 WARNING:    Query graph edge 'e00' has an unexpected property 'category'. Don't know what to do with that, but will continue

and the query_graph was interpreted as if that key+value did not exist.
(the server is not smart enough to recognize that the user meant "predicate": "biolink:physically_interacts_with")
Missing "predicate" is fine, and extra "category" is fine according to the schema.

It seems like there are two alternatives:
- Proceed with what can be interpreted (ideally issuing a WARNING)
- Error out and refuse to do anything if there is an un-understood component to the query_graph

**Comment by edeutsch** [comment]
The decision is documented here:
https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationRules.md

Server SHOULD generate a warning and MAY continue
(SHOULD means recommended but not required)

closing.
