### ISSUE TITLE
How should we address semantic validation of a query_graph?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#210]
A query_graph may be valid according to the schema but semantically invalid.
For example, a QEdge might reference a subject that does not exist as a QNode.
Is a QNode that is not connected to other QNodes by any edge valid?

How should a server react to obvious or perceived flaws in the query_graph?
Should we have some shared code that performs semantic validation on query_graphs?
An open question brought up recently without a proposed solution yet.

**Comment by patrickkwang** [comment]
> How should a server react to obvious or perceived flaws in the query_graph?

It depends on what formatting requirements the particular operation has. There may also be some general, shared requirements, like your example above.

> Should we have some shared code that performs semantic validation on query_graphs?

We can include these validation methods in [reasoner-validator](https://github.com/NCATSTranslator/reasoner-validator) after we define them _somewhere_. Right now that's being done in [Operations and Workflows](https://github.com/patrickkwang/OperationsAndWorkflows/tree/defs/operations#general-message-formatting-requirements).

**Comment by edeutsch** [comment]
Here's an example where validation would help:
https://github.com/NCATSTranslator/minihackathons/issues/176

Ideally the validator would ensure:
- all edges refer to valid nodes in subject_id and object_id
- all node_bindings and edge_bindings refer to valid qnodes and qedges and nodes and edges

**Comment by edeutsch** [comment]
This is ongoing here by Richard: https://github.com/NCATSTranslator/reasoner-validator/issues
Probably don't need an open issue any more, closing for now.
