### ISSUE TITLE
x-translator and SmartAPI

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#216]
After today's Architecture call that demoed some new features at SmartAPI, I check in on my APIs at SmartAPI and I see this:
![image](https://user-images.githubusercontent.com/12707718/110527241-90251d80-80cb-11eb-8548-25d0bc0f50e0.png)

Not good, I suppose. Clicking on the validate link, I see:
![image](https://user-images.githubusercontent.com/12707718/110527318-aaf79200-80cb-11eb-901a-d7c958f3c0fc.png)

Our yaml looks like this:
```
  x-translator:
    component: ARA
    team: Expander Agent
```
and the official TRAPI schema yaml says:
```
  x-translator:
    component: INSERT-EITHER-ARA-OR-KP-HERE
    team: INSERT-TRANSLATOR-TEAM-NAME-HERE
```

So, the question is: why am I seeing this error? I think I am following the official schema.

Ideas?

**Comment by colleenXu** [comment]
You should be compliant if you make team a one-element array, with the element being "Expander Agent".

The official schema that SmartAPI uses is [here](https://github.com/NCATSTranslator/translator_extensions/blob/production/x-translator/smartapi_x-translator_schema.json). Chris Bizon recently requested that teams be an array only (see the closed issues); Chunlei and I reviewed it, brought it up in the Architecture meeting last week, and then approved the change. 

I believe the "TRAPI schema yaml" is somehow not in sync with the JSON schema that SmartAPI is using.
