### ISSUE TITLE
What is our policy on not providing categories/predicates?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#224]
We should address expectations that different teams have as far as queries specifying categories and predicates.

If a QNode provides an id (a CURIE), is the behavior of a KP or ARA different depending on a potential value of category(categories)?
- Can the KP answer if *no* category is specified?
- Does the answer depend on the values of the categories? (if none of the provided categories "fits" the CURIE, is that ignored or does that lead to no response?)

Example: which biolink:Disease are biolink:associated_with CHEBI:6802?
Is the answer different if the QNode:
- provides NO category for CHEBI:6802
- provides biolink:Drug for CHEBI:6802
- provides biolink:ChemicalSubstance for CHEBI:6802
- provides biolink:AnatomicalEntity for CHEBI:6802
?

Is there any way for a client to know whether they can provide NO category for a curie and get a nice result?
should that be specified in /predicates?

Does/should providing no predicate on a QEdge at all yield at least as many answers as specifying a predicate?

I suppose this is partially addressed in: https://docs.google.com/document/d/1sjMen0aq0oFu9u3XHIzaWZgGOBAEBe4kxe_Iz_Gu2tk/edit
scenario 5.
although not completely.

**Comment by bill-baumgartner** [comment]
> Example: which biolink:Disease are biolink:associated_with CHEBI:6802?
> Is the answer different if the QNode:
> 
> * provides NO category for CHEBI:6802
> * provides biolink:Drug for CHEBI:6802
> * provides biolink:ChemicalSubstance for CHEBI:6802
> * provides biolink:AnatomicalEntity for CHEBI:6802
>   ?

It seems to me that by providing an id, e.g. `CHEBI:6802`, a user is being as specific as possible in regards to specifying a query node. The ontology concept referenced by the id is associated with its own definition (or in the case of CHEBI a chemical formula) that establishes the meaning of that concept. If the answer to the question that Eric posed above is `YES, the answer is different depending on the category used` then I think we are saying that by adding a category we are changing the meaning of the underlying ontology concept, and that seems like an unpredictable path to follow.  If both an id and category are specified for a query node, it is my opinion that the category should be considered irrelevant and ultimately ignored. Interested to hear if there are use-cases where this shouldn't be the case however.

> Does/should providing no predicate on a QEdge at all yield at least as many answers as specifying a predicate?

My assumption has been that by not providing a predicate the user is asking for any/all edges that link two nodes.

**Comment by RichardBruskiewich** [comment]
@sierra-moxon might be the best Biolink Model resource input for this issue.

**Comment by edeutsch** [comment]
Addressed in #248. closing
