### ISSUE TITLE
"Upgrading" a scoring attribute from Extended to Core schema

### ISSUE THREAD

**Issue by cartmanbeck** [NCATSTranslator/ReasonerAPI#246]
In order to make it clear that scoring is an important (I would say necessary) part of the results that come back at every level, I would like to make the attribute for score part of the core schema. If a name for the attribute is needed, I would suggest something like "certainty_score", to make it clear that the default metric for a score should be how certain the tool is that they've answered the query sufficiently.

**Comment by edeutsch** [comment]
Addressed in #247
