### ISSUE TITLE
Can non-Biolink Model identifiers be returned as URI's?

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/ReasonerAPI#249]
Are  full URI's (IRI's?) acceptable as identifiers  in  contexts where a CURIE is specified (except for biolink CURIES, which one assumes should always be the required CURIE)?

**Comment by edeutsch** [comment]
@RichardBruskiewich do you have any compelling examples that might motivate this?
At the call 7/22 we thought the answer is no, but perhaps you can add some more detail here or discuss next week?

**Comment by RichardBruskiewich** [comment]
No fine @edeutsch, this is ancient. Can't now recall why it felt compelling at the time. I assume that Translator (e.g. Biolink etc) will have all the CURIE prefixes catalogued for use in the TRAPI JSON, so all contexts where id's are used can constrain to CURIEs.  I'll close this issue now.
