### ISSUE TITLE
Advertise node and edge properties in /meta_knowledge_graph

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/ReasonerAPI#257]
TRAPI now lets a query use constraints to return only nodes or edges that have particular attribute values.

But how are callers to know what are the allowed properties to constrain?

They could (should) be advertised in the /meta_knowledge_graph endpoint, presumably also with some type info.

**Comment by edeutsch** [comment]
Vote here:
https://github.com/NCATSTranslator/ReasonerAPI/discussions/251#discussioncomment-841949
to adjust the priority of this item

**Comment by edeutsch** [comment]
Being addressed in #259
