### ISSUE TITLE
Sending "knowledge_graph": null in a query generates error message

### ISSUE THREAD

**Issue by Sharma05** [NCATSTranslator/ReasonerAPI#258]
SPOKE is complaining about us sending` "knowledge_graph": null ` in a query.

The query we submitted was:  
```
{
  "nodes": {
    "n0": {
      "name": "Chemical Substance",
      "categories": [
        "biolink:ChemicalSubstance"
      ]
    },
    "n1": {
      "name": "aldehyde",
      "ids": "CHEBI:17478",
      "categories": [
        "biolink:ChemicalSubstance",
        "biolink:MolecularEntity",
        "biolink:BiologicalEntity",
        "biolink:NamedThing",
        "biolink:Entity"
      ]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1"
    }
  }
}
```

and we received the error below:

<img width="1054" alt="Screen Shot 2021-06-15 at 4 53 38 PM" src="https://user-images.githubusercontent.com/8516476/122121987-3df64580-cdfa-11eb-80b8-cdeca35e7279.png">

Then we added knowledge_graph and results to null:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "name": "Chemical Substance",
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                },
                "n1": {
                    "name": "aldehyde",
                    "ids": "CHEBI:17478",
                    "categories": [
                        "biolink:ChemicalSubstance",
                        "biolink:MolecularEntity",
                        "biolink:BiologicalEntity",
                        "biolink:NamedThing",
                        "biolink:Entity"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        },
        "knowledge_graph": {
            "nodes": {},
            "edges": {}
        },
        "results": []
    }
}
```

we are getting back the same error as above

**Comment by brettasmi** [comment]
Hi @Sharma05 , if this is specific to SPOKE, I think you should post it over at https://github.com/suihuanglab/spoke-kp/issues instead of here in the specification repository.

**Comment by Sharma05** [comment]
@brettasmi Aah got redirected to reasonerAPI from SMARTAPI and I did not realize. Thank you!.

**Comment by edeutsch** [comment]
We have the same problem in ARAX. I suspect everyone using Python Flask has the same problem. it seems to me that the framework is doing the validation improperly. If anyone knows how to solve this problem, let me know! Because I don't.

**Comment by edeutsch** [comment]
aha, I think the solution is this:
```
x-nullable: true
```
https://connexion.readthedocs.io/en/latest/request.html#nullable-parameters

**Comment by brettasmi** [comment]
Thanks for the quick research @edeutsch! Looks like it was a good idea to post here.

@Sharma05, when I try your second "corrected" TRAPI query, I'm getting a `400: Bad Reqest`, but not because of the `knowlege_graph.` Instead, the error reads as follows:

```
'detail': "'CHEBI:17478' is not of type 'array' - 'message.query_graph.nodes.n1.ids'"
```
so it looks like you'll need to put square brackets around that identifier.

Unfortunately, even with that correction, the spoke kp is still getting an error that I've since isolated. I'll follow up on the on the issue you posted on the SPOKE KP repository.

**Comment by Sharma05** [comment]
> Thanks for the quick research @edeutsch! Looks like it was a good idea to post here.
> 
> @Sharma05, when I try your second "corrected" TRAPI query, I'm getting a `400: Bad Reqest`, but not because of the `knowlege_graph.` Instead, the error reads as follows:
> 
> ```
> 'detail': "'CHEBI:17478' is not of type 'array' - 'message.query_graph.nodes.n1.ids'"
> ```
> 
> so it looks like you'll need to put square brackets around that identifier.
> 
> Unfortunately, even with that correction, the spoke kp is still getting an error that I've since isolated. I'll follow up on the on the issue you posted on the SPOKE KP repository.

so agreed,  I am still getting the same error message after using the square brackets

**Comment by Sharma05** [comment]
> x-nullable: true

@edeutsch Did this work for you?

**Comment by edeutsch** [comment]
yes!

**Comment by Sharma05** [comment]
Thank you @edeutsch

**Comment by edeutsch** [comment]
@Sharma05 okay to close?

**Comment by Sharma05** [comment]
@edeutsch Yes, okay to close.
