### ISSUE TITLE
TRAPI enhancement: Attributes on result bindings

### ISSUE THREAD

**Issue by PhillipsOwen** [NCATSTranslator/ReasonerAPI#264]
The TRAPI model (TranslatorSRI/reasoner-pydantic) currently defines optional "Attributes" on "Knowledge_graph" nodes and edges. Attributes found on result binding nodes and edges have no explicit definition and, as a result, no definitive structure.

I propose that the optional use of TRAPI "Attributes" be extended to "Result Binding" nodes and edges. This addition has a few benefits:
- Enforces a definitive structure when declaring a result binding attribute.
- Extends attributes and properties similarly with its' "Knowledge graph" counterpart.
- Code that currently parses/creates/validates Attributes for knowledge graphs can be leveraged.
- Aids in the comparison of nodes and edges when merging similar results.

Some example attributes stored in the result bindings are (but not limited to):
 - p-values,
 - PubMed article counts,
 - Source databases, 
 - Data provenance,
 - etc...
 
 Thank you for your consideration.

**Comment by vdancik** [comment]
Explanatory ARA expressed need for such attributes as well

**Comment by edeutsch** [comment]
It is not clear to me how a result binding attribute adds value over a knowledge_graph attribute. Are we really so far advanced that the distinction is important?

**Comment by edeutsch** [comment]
Implemented via #269
