### ISSUE TITLE
Adding submitter attribute to TRAPI Query Schema.

### ISSUE THREAD

**Issue by yakaboskic** [NCATSTranslator/ReasonerAPI#282]
I think it would be nice to add a submitter (source) attribute to the TRAPI schema so that ARAs and KPs can see where the source of the message came from. This would be nice in the context of debugging for KPs as often times we can see that a query fails on our system but since we don't know which ARA it came from we don't have a good way to offer suggestions for fixing the message or other steps to remedy the failure. Since we have the infores catalog built for EPC, I think this presents a natural framework to handle this type of attribute in the same way. Namely, have a submitter attribute in the query message that is equal to the infores ID of the submitter.

**Comment by edeutsch** [comment]
Suggested resolution #291 
Comments?

**Comment by edeutsch** [comment]
Solution has been merged. closing.
