### ISSUE TITLE
invalid examples for attribute_type_id

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/ReasonerAPI#290]
`Biolink:has_p-value_evidence` and `Biolink:has_original_source` are given as examples values for `attribute_type_id`, but neither appear in https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml. If I'm understanding everything correctly, I suggest that `biolink:xref` and `biolink:synonym` would be updated and commonly-used `attribute_type_id`s.

https://github.com/NCATSTranslator/ReasonerAPI/blob/42a9d073a92d7aaba0ddf080e461d2da088003fc/TranslatorReasonerAPI.yaml#L559

**Comment by edeutsch** [comment]
addressed in PR #302
