### ISSUE TITLE
How to remodel TRAPI to allow for the merging of messages while retaining EPC

### ISSUE THREAD

**Issue by uhbrar** [NCATSTranslator/ReasonerAPI#313]
Kenny and I have been working for the last little while on coming up with a few plans on how to reduce duplicates in messages. These "duplicate" answers are mostly the same, with the same subject, object, and predicate, but have different EPC information encoded within their attributes, which results in them being unable to be merged without losing information with current TRAPI model. For an example, see this:

<img width="1158" alt="Screen Shot 2022-02-21 at 8 16 36 AM" src="https://user-images.githubusercontent.com/85633484/154962773-cb3d55ad-2878-498d-b9f5-e5a9fbfd8c95.png">

Ideally, this would only result in three answers as shown, but under the current model results in 4. One option for how to rework the model to allow for this is explained here:

[kmorton_translator_thoughts_on_merging.md](https://github.com/NCATSTranslator/ReasonerAPI/files/8109464/kmorton_translator_thoughts_on_merging.md)

Additional refinement will likely be required, however this document does provide the first steps with one option on how approach this issue.

**Comment by edeutsch** [comment]
I put the md file in a PR so I can view it more easily:
https://github.com/NCATSTranslator/ReasonerAPI/blob/edeutsch-issue-313/docs/ideas_from_issue_313.md
