### ISSUE TITLE
Proposed plan for TRAPI 1.3 release

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#329]
Proposed plan for TRAPI 1.3 release:

```
Jun 06 Translator Relay begins
Jun 27 TRAPI 1.3-beta declared ready for implementation
Jul 11 TRAPI 1.3-beta implemented by KPs at test endpoints
Jul 25 TRAPI 1.3-beta implemented by ARAs at test endpoints
Aug 08 TRAPI 1.3-beta implemented by ARS at test endpoints
Aug 15 TRAPI 1.3 released as final
       All TRAPI 1.3 instances released to prod endpoints
       All TRAPI 1.2 instances deleted from prod 1.2 endpoints
```

Comments?

**Comment by edeutsch** [comment]
The sentiment at the TRAPI call on 5/19 is that this draft TRAPI 1.3 release schedule is fine. We will see if any activities at the Relay will affect the planned schedule.

**Comment by edeutsch** [comment]
At the TACT call today, it was approved to proceed with TRAPI 1.3 with Qualifier support and knowledge_type support but no additional support for edge merging or result merging. It's still not clear what that would entail. All 3 proposals are in regions where TRAPI is flexible with additionProperties:true and similar, and so we can be creative using the existing schema.

**Comment by edeutsch** [comment]
I don't think we can freeze on Monday as originally planned. But I think we can freeze after next thursday's TRAPI call if we hustle. So I propose a slight delay with the following schedule. Okay?
```
Jun 30 TRAPI 1.3-beta declared ready for implementation
Jul 14 TRAPI 1.3-beta implemented by KPs at test endpoints
Jul 28 TRAPI 1.3-beta implemented by ARAs at test endpoints
Aug 11 TRAPI 1.3-beta implemented by ARS at test endpoints
Aug 25 TRAPI 1.3 released as final
       All TRAPI 1.3 instances released to prod endpoints
       All TRAPI 1.2 instances deleted from prod 1.2 endpoints
```

**Comment by edeutsch** [comment]
As per 6/30 call, maybe we won't turn off TRAPI 1.2 on august 25. Revisit at that point.

**Comment by edeutsch** [comment]
It has come to attention that I may have been careless with the work "test". I think "dev" would have been a better choice. So without changing the dates, I rephrase to this:
```
Jun 30 TRAPI 1.3-beta declared ready for implementation
Jul 14 TRAPI 1.3-beta implemented by KPs at a dev endpoint
Jul 28 TRAPI 1.3-beta implemented by ARAs at a dev endpoint
Aug 11 TRAPI 1.3-beta implemented by ARS at a dev endpoint
            TRAPI 1.3 code deployed to staging and testing endpoints 
Aug 25 TRAPI 1.3 released as final
       All TRAPI 1.3 code released to prod endpoints
       Reassess how long TRAPI 1.2 endpoints should remain available
```

Does this seem better?

**Comment by vgardner-renci** [comment]
Jun 30  TRAPI 1.3-beta declared ready for implementation
Jul 14    TRAPI 1.3-beta implemented by KPs at a dev endpoint
Jul 28    TRAPI 1.3-beta implemented by ARAs at a dev endpoint
Aug 11   TRAPI 1.3-beta implemented by ARS at a dev endpoint
Aug 18  TRAPI 1.3 code deployed to staging endpoints
Aug 25  TRAPI 1.3 code deployed to testing endpoints 
Sep 1     TRAPI 1.3 released as final
       All TRAPI 1.3 code released to prod endpoints
       Reassess how long TRAPI 1.2 endpoints should remain available
