### ISSUE TITLE
Biolink Model 3.0 release, BMT release to use Biolink Model 3.0 -- July 22

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/ReasonerAPI#346]
Please document issues here

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/tree/v3.0.0 - this is the repo tag for biolink 3.0.
here is the updated model file itself - https://github.com/biolink/biolink-model/blob/v3.0.0/biolink-model.yaml
you can also query the model using the biolink-model-toolkit (which also has a new release for 3.0), here: https://github.com/biolink/biolink-model-toolkit/tree/v0.8.9

**Comment by sierra-moxon** [comment]
@vgardner-renci - I believe this is ready to close, unless we want to use this ticket as an issue collector for issues with biolink-3.0?  If its possible to use the biolink-model issue tracker, that would be my vote :)
