### ISSUE TITLE
KPs update modeling to reflect qualifier changes for chemical -> gene associations. -- Sept 1

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/ReasonerAPI#348]
Please document issues here.

**Comment by andrewsu** [comment]
Can we get a link to the final documentation that describes the qualifier changes?

**Comment by edeutsch** [comment]
The schema changes are here: https://github.com/NCATSTranslator/ReasonerAPI/pull/330/files
and there are some examples here: https://github.com/NCATSTranslator/ReasonerAPI/tree/master/examples/Message
Is that what you are looking for?

**Comment by andrewsu** [comment]
Yes, I think so, thanks @edeutsch!
