### ISSUE TITLE
Add "inferred" to meta knowledge graph?

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/ReasonerAPI#363]
Some KPs are capable of answering creative queries.    Can we use the meta knowledge graph endpoint for those KPs to advertise the capability?

**Comment by edeutsch** [comment]
Yes, already in TRAPI 1.3-beta here:
https://github.com/NCATSTranslator/ReasonerAPI/blob/07a4a1afea723ff465e28cb1c72d3d2e8821e6c5/TranslatorReasonerAPI.yaml#L985-L1027

**Comment by cbizon** [comment]
Oh, great.  Thanks for pointing that out!
