### ISSUE TITLE
Add `nullable: true` to NodeBinding.query_id

### ISSUE THREAD

**Issue by gaurav** [NCATSTranslator/ReasonerAPI#366]
The documentation of NodeBinding.query_id says that this is "An optional property" and that under certain circumstances "this query_id MUST be null or absent". I think it would be useful to add a `nullable: true` to the definition to make it clear that this field can be null.

https://github.com/NCATSTranslator/ReasonerAPI/blob/7520ac564e63289dffe092d4c7affd6db4ba22f1/TranslatorReasonerAPI.yaml#L481-L492

**Comment by edeutsch** [comment]
This issue was addressed in PR #367, closing.
