### ISSUE TITLE
Convert every allOf tag to oneOf in OpenAPI schema

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/ReasonerAPI#372]
TRAPI 1.3 validation was problematic with `jsonschema` (inside the reasoner-validator) due to the use of `allOf` OpenAPI schema property alongside `nullable: true`. 

Review of the [**definitions for allOf versus oneOf** ](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) suggest this is a reasonable revision, given that logically, one cannot satisfy _both_ a concrete non-null JSON data model and a null value, at the same time, but rather, choosing one **or** the other (i.e _non-empty schema_  **xor** `null`, i.e. `oneOf`) is a more reasonable semantic expectation.

**Comment by edeutsch** [comment]
Addressed in #403
