### ISSUE TITLE
How will we resolve the desire to encode additional information beyond the original question?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#379]
In an answer to a question like: Which drugs (might possibly) treat disease X?
A straight lookup might produce results that have the same structure as the query graph.
But in creative mode (and perhaps in a fuzzy area between lookup and creative mode), there is often a desire to add additional nodes and edges of information that don't conform to the query graph? Here seem like 4 ways to do it:
1) You MUST NOT do it
2) Expand the query graph to encompass the results (the ARAX way)
3) Add additional nodes and edges in the KG and Results but the Results.*bindings are not bound the query graph (Aragorn way)
4) Add some new feature to TRAPI to allow each Result to have its own entire KG as "supporting information" for an edge

This has been discussed at length in the Architecture series but I am not aware of a final decision (although some think we decided on option 4?)

When a final decision is documented, TRAPI may need to change in some way to accommodate it.

**Comment by edeutsch** [comment]
The framework for how I'm thinking about this is depicted in slides 13-17 at: https://docs.google.com/presentation/d/14BfQS72VWQr0P6Mv1Zcj09zrGBKaqTUwqNffKJQkfXA/edit

**Comment by ehinderer** [comment]
I believe the plan for xARA is in line with number 2, the query graph is modified so that edge and node bindings can still be made in the results.

**Comment by edeutsch** [comment]
Addressed in PR #389
