### ISSUE TITLE
Standard/conventions for representing supporting publications

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/ReasonerAPI#398]
Testing efforts have identified variability w.r.t. how publications and other documents are represented as support for Edges and Study Result objects in TRAPI messages.   The Biolink Model provides two edge properties ( `supporting_document`, and its child `publications` - which are the topic of the Biolink ticket [here](https://github.com/biolink/biolink-model/issues/1107)), as well as a `Publication` class. 

**Here. I would like to finalize and document conventions for how these elements are applied in Attributes in TRAPI messages to structure this type of information.** 

### Questions/Issues:

1. **When to use these different properties?**  _(ignore for now - as we are [voting here](https://github.com/biolink/biolink-model/discussions/1234) on whether to have two properties at all))_

2. **How to represent the value of these properties?** 
     a. Current convention is to use established document identifiers such as pmids, pmc ids, dois, etc.  Should there set an order of preference here, or a requirement to use one over another (e.g. if a pub has a PMC id and PMID, always use the PMID)?  Do we have a resource that maps between different types of identifiers for documents/publications?

3. **In cases where there are multiple documents/pubs supporting a given Statement or Study Result, should these be captured as a list/array of document identifiers in the `Attribute.value` field, or one at a time in separate Attribute objects?**  
     a.  It was decided earlier that separate attributes were best - as this would allow for additional metadata about each publication to be captured in other Attribute fields (e.g. url, description/title, etc). But it wasn't clear if this was a requirement or recommendation?
     b. In practice, most KPs are providing lists of pmids in a single Attribute - esp in cases where there are very many supporting pubs (can be tens to hundreds in some cases).  But the format/syntax used to represent such lists is varibale (e.g. a single string vs formal array of object references?  if a string, use of comma vs pipe delimiters?)

4.  **Where/how should we capture additional metadata about a publication (e.g. title, year, url, MeSH terms, journal, authors, etc)?**
     a. Some of the use cases for applying such additional publication info are outlined in the [ticket here](https://github.com/NCATSTranslator/Feedback/issues/79#issuecomment-1405617155) - most relate to supporting O& O for ordering results, and which pubs to show first for a given result. 
     b. Some of this info could be captured using Attribute fields such as `value_url` or `description` (see json example below) - but this doesn't work if we allow multiple pubs as a list in a single Attribute object.  
     c. But TMKP already provides a publication metadata API that provides the types of info listed [here](https://github.com/NCATSTranslator/Feedback/issues/79#issuecomment-1426084782) - so representing an yof this in the `publications` Attribute seems duplicative.
     d.  @bill-baumgartner I assume here that Publication/Documents are represented as instances of Biolink:Publication, which has a collection of node properties for describing things like title, authors, etc?

````
{
  "attribute_type_id": "biolink:publications",    
  "value":  "PMID:32961480",                                  
  "value_type_id": "biolink:Publication",    
  "value_url":  "https://pubmed.ncbi.nlm.nih.gov/32961480/",
  "description": Review article, "Discovery of novel liver X receptor inverse agonists as …",
  "attribute_source": "infores:molecular-data-provider"
}
````

**Comment by mbrush** [comment]
**Related issue:** how to represent Cinical Trials that support an Edge/Statement.  At present, some KPs are using the `publications` slot to capture NCT clinical trial ids - but these ids represent trials, not publications:

![image](https://user-images.githubusercontent.com/5184212/221961591-951200eb-42e9-4b0a-bcdf-355713214043.png)
 (note that this KP is actually using  the `biolink:Publication` class as the attribute_type_id instead of the `publications` slot). 

We need to decide if we want to allow this (requires considering something like NCT00494715 to be a document or publication describing a clinical trial, rather than the clinical trial itself), or define distinct modeling to allow linking an edge to a supporting clinical trial.

**Comment by edeutsch** [comment]
Is it the mere existence of the clinical trial that is providing the evidence or is it the published outcome/report of the clinical trial that is providing the evidence? I would imagine the latter? Perhaps it is the final report (I assume there always is one? I don't actually know) from the trial that should be cited as a publication? Perhaps these identifiers identify studies, yes, but most crucial identify the published outcome?

**Comment by mbrush** [comment]
There are also considerations about the form/syntax of the value for a CT.gov record.  Currently referenced as a string representing the identifier, e.g.  NCT00222573.  Should we require a CURIE or URL form of this be captured?   Bioregistry.io already defines one we could use, and an expansion. See  https://bioregistry.io/registry/clinicaltrials.  

Assuming this means we can require CURIE/URL-based representation of clinical trials, consider the concrete proposals below for how we reference supporting clinical trials.  Examples below show supporting clinical trials alongside references to publications referenced as CURIEs/URLS vs free text, per the decision to split these into separate Attribute objects here. 


### Option 1: Consider clinical trial record ids to be Publications, and capture them using the `publications` edge property.

````
# Attribute containing pubs referenced by CURIE or URL (which here include NCT records)
{
  "attribute_type_id": "biolink:publications",            
  "value": [
           "PMID:31737390",
           "PMID:6815562",     
           "http://info.gov.hk/gia/general/201011/02/P201011020204.htm",
           "clinicaltrials:NCT00222573",
           "clinicaltrials:NCT00503152"
           ]                                      
  "value_type_id": "biolink:Uriorcurie",    
  "attribute_source": "infores:hmdb"
}, 

# Attribute containing pubs referenced as free text
{
  "attribute_type_id": "biolink:publications",           
  "value": [
            "Thematic Review Series: Glycerolipids. Phosphatidylserine and phosphatidylethanolamine in mammalian cells: two metabolically related aminophospholipids",  
            "Toranosuke Saito, Takashi Ishibashi, Tomoharu Shiozaki, Tetsuo Shiraishi, 'Developer for pressure-sensitive recording sheets, aqueous dispersion of the developer and method for preparing the developer.' U.S. Patent US5118443, issued September, 1986.: http://www.google.ca/patents/US5118443"
           ],                                  
  "value_type_id": "string",    
  "attribute_source": "infores:hmdb"
}
````

-----------


### Option 2: Consider clinical trial record ids to represent the study/trial itself, and capture using a `supporting_studies` edge property .

````
# Attribute containing pubs referenced by CURIE or URL (which here do not include clinical trial records)
{
  "attribute_type_id": "biolink:publications",            
  "value": [
           "PMID:31737390",
           "PMID:6815562",     
           "http://info.gov.hk/gia/general/201011/02/P201011020204.htm"
           ]                                      
  "value_type_id": "biolink:Uriorcurie",    
  "attribute_source": "infores:hmdb"
}, 

# Attribute containing pubs referenced as free text
{
  "attribute_type_id": "biolink:publications",           
  "value": [
            "Thematic Review Series: Glycerolipids. Phosphatidylserine and phosphatidylethanolamine in mammalian cells: two metabolically related aminophospholipids",  
            "Toranosuke Saito, Takashi Ishibashi, Tomoharu Shiozaki, Tetsuo Shiraishi, 'Developer for pressure-sensitive recording sheets, aqueous dispersion of the developer and method for preparing the developer.' U.S. Patent US5118443, issued September, 1986.: http://www.google.ca/patents/US5118443"
           ],                                  
  "value_type_id": "string",    
  "attribute_source": "infores:hmdb"
},

# Attribute containing supporting clinical trials
{
  "attribute_type_id": "biolink:supporting_studies",           
  "value": [
           "clinicaltrials:NCT00222573",
           "clinicaltrials:NCT00503152"
           ],                                  
  "value_type_id": "biolink:Uriorcurie",    
  "attribute_source": "infores:hmdb"
}
````

**Comment by edeutsch** [comment]
I don't have a strong opinion, but I think I'm liking option 1. It depends a little on my abstract question above to which there was no answer provided:
> Is it the mere existence of the clinical trial that is providing the evidence or is it the published outcome/report of the clinical trial that is providing the evidence? I would imagine the latter? Perhaps it is the final report (I assume there always is one? I don't actually know) from the trial that should be cited as a publication? Perhaps these identifiers identify studies, yes, but most crucially identify the published outcome? Again, I don't know myself. Can someone shed light on this?

**Comment by mbrush** [comment]
**May 22 Update:**
------

Clinical trial records in clinical-trials.gov are often referenced as support for edges reporting a drug to treat a condition.
e..g "NCT00222573".  In recent discussions we settled on a specific CURIE syntax with which to reference clinical trials as reported in registries like clinical-trials.gov, in the `Attribute.value` field:
```json
"value": "clinicaltrials:NCT00222573"
````

We also decided that any URLs that allow users to link directly to the ct.gov site to explore these clinical trial records should be 
captured in the `Attribute.value_url` field:
```json
"value": "clinicaltrials:NCT00222573"
"value_url": "https://clinicaltrials.gov/search?id=%22NCT03074773%22"
````

The specific question we want to focus on now is whether this Attribute object should use the existing `biolink:publications` edge property as its `attribute_type_id`, or we should use an edge property like `biolink:supporting_studies' (which reflects the fact that this is an instance of a performed study/trial whose results support the 'treats' edge).

Concrete examples of these competing proposals are presented below - showing how supporting trials would be represented alongside supporting publications for both approaches:  


### Option 1: Consider clinical trial record ids to be Publications, and capture them using the `publications` edge property.

````
# Attribute containing pubs referenced by CURIE or URL (which here include NCT records)
{
  "attribute_type_id": "biolink:publications",            
  "value": [
           "PMID:31737390",
           "PMID:6815562",     
           "http://info.gov.hk/gia/general/201011/02/P201011020204.htm",
           "clinicaltrials:NCT00222573",
           "clinicaltrials:NCT00503152"
           ]                                      
  "value_type_id": "biolink:Uriorcurie",    
  "attribute_source": "infores:hmdb"
}, 
````

-----------


### Option 2: Consider clinical trial record ids to represent the study/trial itself, and capture using a `supporting_studies` edge property.

````
# Attribute containing pubs referenced by CURIE or URL (which here do not include clinical trial records)
{
  "attribute_type_id": "biolink:publications",            
  "value": [
           "PMID:31737390",
           "PMID:6815562",     
           "http://info.gov.hk/gia/general/201011/02/P201011020204.htm"
           ]                                      
  "value_type_id": "biolink:Uriorcurie",    
  "attribute_source": "infores:hmdb"
}, 

# Attribute containing supporting clinical trials
{
  "attribute_type_id": "biolink:supporting_studies",           
  "value": [
           "clinicaltrials:NCT00222573",
           "clinicaltrials:NCT00503152"
           ],                                  
  "value_type_id": "biolink:Uriorcurie",    
  "attribute_source": "infores:hmdb"
}
````

In making a decision, consider how the Clinical Trials KP being developed by the Multiomics team will represent these clinical trial records in their data (as information entities (pubs / records), or as research activities (studies/trials) - and aim to apply consistent semantics across these representations.

**Comment by gglusman** [comment]
Note the 'value_url' as shown ( https://clinicaltrials.gov/search?id=%22NCT03074773%22 ) doesn't work.
For the current version of the system the URL would be: https://clinicaltrials.gov/ct2/show/NCT03074773
Looks like they're developing a new version, and under it, the URL seems to be: https://beta.clinicaltrials.gov/study/NCT03074773

**Comment by mbrush** [comment]
Thanks Gustavo - I used the search syntax in my examples only because this is the format of the links we get from sources like chembl as provided by MolePro.  Ideally we would want to point people directly to individual trial pages.  And good to know about the new version in development.  I;d like to find out more about this from you or Kamileh.

**Comment by gglusman** [comment]
To clarify, the new version appears to be just for their UI.
You get prompted to try it when accessing the old one.

**Comment by mbrush** [comment]
Outcome of 5-23-23 EPC Call - general preference for 'supporting_study' as the long term solution, but may have to wait to implement until after September as KPs may not be able to regenerate data to be compliant with this specification before then.  In mean time, modeling team will get required edge property into Biolink, and draft an initial specification for representing supporting clinical trials / studies in TRAPI.

**Comment by mbrush** [comment]
Closing with the creation of the [supporting_publications_specification](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationGuidance/Specifications/supporting_publications_specification.md)- but as noted in the spec, we need to return to this and modify the specification for how to reference supporting clinical trials. I created #447 as a separate ticket for this issue.
