### ISSUE TITLE
Version number disagreement

### ISSUE THREAD

**Issue by vdancik** [NCATSTranslator/ReasonerAPI#448]
The version of TRAPI that is tagged as 1.4.2 does not match the the version in the yaml file (1.4.0):

https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L25

**Comment by edeutsch** [comment]
It's true. But that seemed preferable to inviting the chaos of some actors claiming 1.4.0 and some 1.4.2. Version 1.4.2 only differs from 1.4.0 in ways to keep the TRAPI validator happy.

**Comment by edeutsch** [comment]
At the TRAPI call on 8/18/2023, we clarified that we all agreed to continue using "1.4.0" as the listed TRAPI version of record for implementations, although the validator is using 1.4.2, which remedies some obscure JSON schema items that hinders validation.
