### ISSUE TITLE
Best way to represent a gene set or gene sets using the Reasoner API graph standard?

### ISSUE THREAD

**Issue by realmarcin** [NCATSTranslator/ReasonerAPI#57]
one option I think is to store all pairs but maybe something better?

**Comment by patrickkwang** [comment]
Can you clarify your question? Are you looking to ask a question about a specific set of genes, or obtain a set of genes as the answer to a question, or something else?

**Comment by vdancik** [comment]
milestone: 1.1

**Comment by patrickkwang** [comment]
#149
