### ISSUE TITLE
response tool_version

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#6]
In version 0.6, Michel Dumontier commented:
response tool_version: better is to provide a url to the release

**Comment by patrickkwang** [comment]
Agreed.
e.g. https://github.com/RTXteam/RTX/releases/tag/0.1

**Comment by vdancik** [comment]
Should be provided by metadata endpoint #142

**Comment by edeutsch** [comment]
This seems stale and unused except for ARAX. Any objections to closing?
