### ISSUE TITLE
Must the query_graph's match?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/ReasonerAPI#66]
Hi everyone, this is a continuation of the discussion that we had at the June 17 KGS call. The background is this: via the 0.9.1 reasoner API, a client can issue a question in the form of a query_graph, and the reasoner will return a response message containing a query_graph and a knowledge_graph and a set of results (answers) to the question where is result (answer) is a binding of knowledge_graph ids to query_graph ids.

A presumed unspoken rule is that the returned query_graph from the reasoner should be exactly the same as the client's query_graph. It seems like we have three options:

A) The returned query_graph must be identical to the uploaded query_graph
B) The returned query_graph must be identical except that exact synonyms be be substituted
C) The reasoner has some leeway in returning a slightly different query_graph

Here's a specific example:
Let's say the query is "Which symptoms are associated with malaria?"
This might be translated to DOID:12365 -> has_phenotype -> "phenotypic_feature"s?
Let's then suppose that my KG just has DOID:12365 as a bland parent term for several types of malaria, but doesn't actually have phenotypes associated with it. But its child term cerebral malaria does.
And let's suppose that my reasoner wants to say that if I have some phenotypic features of cerebral malaria, those will also apply to malaria (and making the leap from symptom to phenotypic_feature). What should or *can* the response be?

1) Strict: the user asked for DOID:12365, and the reasoner's KG does not have has_phenotype relationships for DOID:12365, so no soup for you! 0 results.
2) The inference: the user asked for DOID:12365, but the reasoner will map some relationships from children to the parent and preserve the query_graph and give inferred answers linked to DOID:12365
3) The query revision: The reasoner sends back a different query_graph that now includes the child term cerebral malaria and the relationships the KG has for that.

It seems that we would benefit from a shared agreement on what should or can happen, and perhaps that should be codified in the validator. We discussed some possibilities where (1) and (3) might be separated by different endpoints (say /query is (1) and /fuzzy_query is (3)) or alternatively, there could be just one endpoint /query with a user-settable flag in the submitted message that either allows or disallows query_graph changes.

What say ye?

**Comment by patrickkwang** [comment]
I'm in favor of option C - no restrictions. As long as the message structure is respected and it is clear what each reasoner service will do, we retain the ability to merge/compare/pipeline reasoner services. We can leave decisions about curie/concept specificity to the user by choosing which service, endpoint, or flags to use.

**Comment by srensi** [comment]
Questions: 
(1) Are we considering only the types of "moves" described in the example? 
(2) What are the benefits of returning a "mutated query graph"?

Opinions:
Users generally expect the sensitivity and specificity of the result to reflect the query.  

Moving down the tree - If they use a general term they probably want/need high sensitivity.  So including child annotations is a behavior that could be reasonably expected or inferred by the end user.  You could probably get away with doing everything "under the hood" (i.e. invisible to end user) and it wouldn't be much of a problem.  Whether you would want to do it like that depends on the needs of the developers imo.

Moving sideways - If they use specific terms, I think the assumption has to be that they want high specificity, and including siblings or similars is not expected default behavior.  Something like this is useful depending on whether I am getting anything back from my specific search.  I see it as basically equivalent to a "get similar" operation composed with a "normal" query.  Should the "mutation" be its own operation/module in this case.  If they are composed as a single function, then I would want to get the mutated query graph back.

Moving up - Parent terms I think are most useful when you have a list of specific terms that you want to group together (i.e. clustering + enrichment).  I'm not sure this is relevant to our discussion.

**Comment by edeutsch** [comment]
Anyone else have a comment?

I agree that moving down the tree is the most obvious and applicable.

Should our default policy be to allow option C, with a suggestion that anything other than moving down the tree should be treated with caution?

**Comment by MarkDWilliams** [comment]
I'm fine with something between B and C, with the caveat that if we do opt for option C (and this is more of a UX issue than a KGS one), we need to notify the user in some way that the graph has been altered.

**Comment by vdancik** [comment]
I believe C) is best option - we need to allow reasoners to answer as they see fit and not be restricted by a structure of a question.

**Comment by cbizon** [comment]
I think that (C) is best, but I think it would also be good if there was one more binding step that matched the asked question nodes to the answered question nodes.
So if I asked for 
A-B-C
and I got back
Q-R-S-T
It would be good to know that e.g. T=C, A=Q, R=B and S is a new node.

**Comment by patrickkwang** [comment]
@cbizon, three ideas:

1. A natural way to convey some of this without explicitly providing extra bindings would be in the qnode ids themselves: (A)-(B)-(C) becomes (A)-(B.1)-(B.2)-(C)

2. Alternatively, or perhaps additionally, we could include a designated space for reasoners to report "what I did and why/how I did it". The response object currently looks like this:
```
query_graph: {}
knowledge_graph: {}
results: []
```
but we could instead do:
```
message:
  query_graph: {}
  knowledge_graph: {}
  results: []
rationale: {}
```

3. One more crazy idea is to break the question-fuzzing and the question-answering into separate steps and in the first one treat your modified question as a result. The client would be responsible for translating that result into the question for the second step.

**Comment by cbizon** [comment]
Looking back at the discussion, my opinion is still on this should be allowed, and we need to capture what happened.  

If we consider that the API does not really define an operation, but a format for transferring graphs, then the question maybe can be rephrased a bit as, "what are the operations in which a query graph might be changed?".   So for instance, maybe changing a query graph is an operation by itself (Patrick's idea 3 above).  Or maybe a "fill in the blank" query with / without graph querying might be different operations.   Then tools can expose what they are going to do re: changing questions.

Maybe if the operations are clear then the changes to the format become clear?

**Comment by ehinderer** [comment]
> I think that (C) is best, but I think it would also be good if there was one more binding step that matched the asked question nodes to the answered question nodes.
> So if I asked for
> A-B-C
> and I got back
> Q-R-S-T
> It would be good to know that e.g. T=C, A=Q, R=B and S is a new node.

If the KP is allowed to return a "KP_modified_query_graph" object with these conversions clearly delineated then the ARA could return it, along with the results back to the user without ambiguity. A flag can be raised to the user that the query was modified in some way and that object could serve as a way to track changes. You could even have a property as part of that object that tells _which KP made the modification_ to maintain a paper-trail. 

The way I envision it is that the ARS only needs to look for a "KP_modified_query_graph" object from the KP. If it finds one, then it should return it to the ARS/user along with the ranked responses. Otherwise, assume the query wasn't modified and return the identical query graph back along with the responses.

**Comment by patrickkwang** [comment]
I'd like to include this in the 'operations' discussion. If a specific operation allows or requires modifying the query graph, that should be specified in the operation definition.

Closing in favor of #152.
