### ISSUE TITLE
tighten up `required` and `additionalProperties`

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#92]
Making desired properties optional and additional properties permitted leads to perhaps puzzling behavior. Mis-named properties are then not validated at all.

For example, [this](https://github.com/NCATSTranslator/KnowledgeProviderScaffold/blob/4b5ee43956fce22e295e3bd62920419e19fc06d8/TranslatorKnowledgeProviderResponseScaffold.json) validates against the 0.9.2 spec, despite providing `answers` instead of `results`, and formatting the contents differently.

**Comment by edeutsch** [comment]
I agree.
One option would be to remove additionalProperties from everywhere, have a good ongoing discussion about what we will permit in the (maximal) _optional form of the standard, and then validate against the optional form. That way, if someone wants to add something, it will be a group discussion about if adding it is reasonable and that there's only one way to do something (i.e. not that two different groups do the same thing in two different ways). And anything not in the maximal version is illegal. All servers would still be only obligated to implement the minimal version and then pick and choose from optional.
Does that sound like a good strategy?

**Comment by patrickkwang** [comment]
That's a reasonable approach to validating the various JSON components.

Note that we will have to explicitly specify `additionalProperties: false` in the optional document, since `additionalProperties: true` is actually the default behavior.

**Comment by patrickkwang** [comment]
#153
