### ISSUE TITLE
Reasoner Standard and long-running processes

### ISSUE THREAD

**Issue by denisemauldin** [NCATSTranslator/ReasonerAPI#96]
Currently the Reasoner Standard includes one API call that has a message object with query_graph, knowledge_graph, and results fields.  The BigGIM Knowledge Provider is a series of BigQuery tables with a BigGIM API that interfaces with them.  These queries typically take less than a minute, but this depends on the query complexity.  Therefore when the BigGIM API is queried, it returns a request ID that can be used to retrieve the information after the secondary query to BigQuery is complete.  

When using the BigGIM API, we submit the query, get the request ID, poll the status endpoint until the job status is complete and then query the results endpoint with the request ID to retrieve the results.  The Reasoner Standard currently does not support this workflow.  What modifications would be needed to support long-running processes?

Currently we have implemented an initial endpoint that accepts the query submission as a POST to the /query endpoint that requires a query_graph field (optionally supports a knowledge_graph field) and returns the request ID.  The next step seems to be to allow a GET to the /query endpoint to return the message object that includes the query_graph, knowledge_graph, and results fields.  The results field would be empty until the BigQuery process completed.  Is this a reasonable step towards supporting the Reasoner Standard?

**Comment by edeutsch** [comment]
In version 0.9.1 of the Reasoner Standard:
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/v0.9.1/API/TranslatorReasonersAPI.yaml
The Query class had an attribute "asynchronous" to be used for this very purpose. If the client sets this flag to true, the an empty message is returned quickly and the Message id can be used to poll the /message endpoint for its completion.

Upon looking closely at version 0.9.2 of the schema in the repo, it looks like that functionality was removed, accidentally I assume.
So I recommend implementing it that way, but it is open for discussion.

**Comment by edeutsch** [comment]
Discussed on weekly call and decisions implemented in #255
