### ISSUE TITLE
Data Version

### ISSUE THREAD

**Issue by denisemauldin** [NCATSTranslator/ReasonerAPI#97]
The TranslatorReasonersAPI_optional.yaml file has Message fields for tool_version and schema_version, but what about data version or data provenance?  KPs that ingest or provide data from many data sources will have multiple versions of data or provide snapshots/releases of data sources after milestones in the research/data generation.  What is the expectation when KP data changes over time?

Should version or provenance fields be mandatory in the result?

Can version be used to query a KP?  For example, if release 2020-03-19 included a gene interaction of interest but release 2021-03-01 did not, would a user be able to specify optionally a version?

**Comment by edeutsch** [comment]
Hi Denise, I can provide my thoughts, although others may disagree.

First one question for you: are you trying to use the standard to provide results from a reasoner or provide results as a knowledge provider? Sorry if that is a silly question, but somehow I'm wondering if you're trying to provide information as a KP using this standard? This ReasonerStdAPI is designed for reasoner (ARA) output, not KP output.

To your questions:
> What is the expectation when KP data changes over time?
I think KPs should definitely tag their data with a release date.

> Should version or provenance fields be mandatory in the result?
A ReasonerStdAPI Message has tool_version, schema_version, datetime to describe when the reasoner performed its work and provided an answer to a user query. Within the KnowledgeGraph in the Message, each edge (which is basically an assertion about the relationship between two entities) should have provenance information. Each edge can have:
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/9b62d4027795ea2a8314600c4a20468bf45bf7b9/API/TranslatorReasonersAPI_optional.yaml#L821
        "is_defined_by": "ARAX",
        "provided_by": "ChEMBL",
       "defined_datetime": "2020-01-12 02:21:27",
       "evidence_type": "ECO:0000220",
These are not strictly required, but are strongly encouraged.
i.e. every assertion made in the KnowledgeGraph should have provenance information, yes.

> Can version be used to query a KP? For example, if release 2020-03-19 included a gene interaction of interest but release 2021-03-01 did not, would a user be able to specify optionally a version?

I would say that would be up to the KP. In my experience most KPs just provide their latest best data. Reasoners should just relay that versioning information in every assertion they provide in their KnowedgeGraph.

Currently I am not aware of any NCATS Reasoners that are capable of answering a query based on information that was valid at some point in the past.

Does this answer your questions?

**Comment by denisemauldin** [comment]
Hi Eric,

Thanks for asking that question.  Our understanding so far is that, while standards for KPs are still being determined, the Reasoner Standard API is one option.

https://docs.google.com/document/d/1KiXoJT1T05xZMYuzFvid2-cNOIovPZuWQ4_V3mUT_Nw/edit
 
Are you aware of another standard, or do you have recommendations as an ARA on what you’d like to see from a KP?

Thank you for answering the question regarding provenance data included in the knowledge_graph.  Why is it not required rather than being optional?  Is there an example of a well-formed response that includes the strongly recommended optional fields as well as the required fields?

Is it outside the goal of the NCATS Reasoners to do comparisons over time of knowledge development then?  What happens if there's a major change in understanding about a particular disease/gene/etc and results for GeneToDisease association shift after this change?  Or are NCATS Reasoners a snapshot of current events that should be queried frequently?

**Comment by patrickkwang** [comment]
Versioning/provenance is definitely a huge unresolved issue in the entire Translator modeling and communications framework. I don't have a solution. But regarding whether any of these provenance fields should be required or optional, I'm in the 'optional' camp. Assertions may be true and useful even if we don't know how or when or whence they came. If a specific ARA would like to impose more stringent requirements on the KPs with which it cooperates, that's probably fine.

We have a separate documentation problem making it difficult for implementers to discover these things because they are buried in the extensive '_optional' spec. See #99. Related to #93.

**Comment by edeutsch** [comment]
Vlado will post issue in Biolink Model repo with a link to this closed issue
