### ISSUE TITLE
results field: associations with multiple slots

### ISSUE THREAD

**Issue by denisemauldin** [NCATSTranslator/ReasonerAPI#98]
Let's say the ARA has access to data calculated at three confidence levels. There seem to be two methods to return information for the confidence level.

1) options - As the query specification doesn't prevent additional fields, many ARA have added options or query_options fields to handle parameters.  Thus we could filter the knowledge_graph with an optional options field to specify that all of the results of the query were at a specific confidence level.  

2) knowledge_graph - The BioLink model has slots on associations and one of these is the has_confidence_level term - https://biolink.github.io/biolink-model/docs/has_confidence_level.html
If the knowledge_graph contained all of the information and I'm understanding the BioLink model correctly, this would mean that each knowledge_graph edge would have three entries, one per has_confidence_level.  

Is one method preferred over the other?  Is support for both methods useful?  This could be a specific example of when there is multiple results for any association slot.

**Comment by patrickkwang** [comment]
What is different about the edge based on the confidence level? Is there some metric computed based on the desired confidence, e.g. `xxx_p50`, `xxx_p90`, and `xxx_p99`? My feeling is that, in this case, there should be one edge with an attribute for each confidence level, rather than three edges. This is a data modeling question as well as a syntax question; perhaps @balhoff or @cmungall have opinions?

You could allow clients to specify which confidence levels should be returned via the `options` field, if you like.

**Comment by patrickkwang** [comment]
@denisemauldin Can you give examples of what this sort of data could look like?

**Comment by denisemauldin** [comment]
@patrickkwang We have gene pair correlation data that has been calculated at multiple different confidence levels.  An example could be a link between KLK3 and FN1 that appears with three different confidence levels of 0.5, 0.1, and 0.001

**Comment by edeutsch** [comment]
I'm not fully understanding this example. I'm thinking that the assertion is:
[mRNA abundance of] KLK3 is positively correlated with [mRNA abundance of] FN1 in liver tissue with a confidence of p-value = 0.00084
Is that what you have?
Is the result that this p-value survives level cutoffs of 0.5, 0.1, and 0.001 somewhat irrelevant to the primary assertion?

**Comment by denisemauldin** [comment]
BigGIM analysis was done at three different confidence levels.  So the BigGIM dataset would have these three associations:

[mRNA abundance of] KLK3 is positively correlated with [mRNA abundance of] FN1 in liver tissue [has_confidence_level] 0.01

[mRNA abundance of] KLK3 is positively correlated with [mRNA abundance of] FN1 in liver tissue [has_confidence_level] 0.05

[mRNA abundance of] KLK3 is positively correlated with [mRNA abundance of] FN1 in liver tissue [has_confidence_level] 0.1

**Comment by edeutsch** [comment]
Is that any different than saying:
[mRNA abundance of] KLK3 is positively correlated with [mRNA abundance of] FN1 in liver tissue [has_confidence_level] < 0.01
?

i.e. if it's true at 0.01, is it not automatically true at 0.05 and 0.1?

**Comment by denisemauldin** [comment]
@edeutsch Right now BigGIM accepts a parameter that allows each request to pick the confidence level that they want to query.  Some relationships are present at some levels but not at others.  I haven't done the analysis to see if the relationships are present at 0.01 that they're also present at 0.05 and 0.1 though that would make sense.  This was mostly a query to see what happens in the results if there are multiple values for a particular slot.  It seems like the answer is to pick the best option and add that to the result?

**Comment by edeutsch** [comment]
I would need to understand more about BigGIM before I can say more. I am supposing that there is just one value, but to speed up queries, it is perhaps organized in 3 sets? I don't know.
