### ISSUE TITLE
User-friendly documentation

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/ReasonerAPI#99]
Reading the OpenAPI yaml is currently the only way to get up-to-date information about the standard. It would be nice to have something

1. more human-readable
2. more easily searchable
3. with more internal and external hyperlinks
4. prettier

**Comment by edeutsch** [comment]
Does autogen swagger endpoint documentation like this:
https://arax.rtx.ai/beta/api/rtx/v1/ui/
count for most of these? Obviously that site includes our own customizations and additions, but it would not be too difficult to autogenerate such for the minimal and the optional YAMLs and have it available. Would that be a good start?

Note also that there is a pptx which is definitely 1 and 4:
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/master/API/ReasonerStdAPI_0.8.0to0.9.1.pptx
 I have a more up-to-date one that I haven't checked in. But I could check it in if anyone besides me uses these.

**Comment by patrickkwang** [comment]
I could add two more desiderata:

5. editable/versionable
6. viewable online

For those reasons, I'm not a fan of PPTs. Auto-deploying a Swagger UI is intriguing. I like that it would be tied directly to the formal definition. I think newer versions of Swagger UI are even more accessible, e.g. http://robokop.renci.org:4868/ui/

I see two problems right away, though:

* it is even less searchable than the yaml
* it still keeps our required and optional specs separated

I suppose I was imagining something like this:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
That achieves 1, 3, 4, 5, and 6. I don't know that it is _more_ searchable than the yaml, but the hyperlinks help me a lot. To improve searchability over a plain text file, we'd really need a dedicated search tool, so I'm willing to forgo that one.

One problem with an independent Markdown file is in keeping it aligned with any more formal definition(s). We could decide that the README is the authoritative standard and provide JSON schema only as auxiliary assistance for validation, as OAI has done. Or some hybrid approach.

**Comment by edeutsch** [comment]
And there is of course the README.md here:

https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/tree/master/API

It is out of date and rather barebones. But spending some time on this would help many. And writing a script that converts the YAML into MD would be pretty easy and would force better documentation in the YAML itself.

**Comment by edeutsch** [comment]
I think this is all taken care of by #278 and prior work. okay to close?
